---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tcsjenja/CENTAR-TRZNI
    - /bin/mkdir -p $DEPLOYPATH/backend
    - /bin/cp -R backend/. $DEPLOYPATH/backend/
    - /bin/rm -rf $DEPLOYPATH/build
    - /bin/cp -R build $DEPLOYPATH/
    - cloudlinux-selector set --json --interpreter nodejs --user tcsjenja --app-root CENTAR-TRZNI/backend --startup-file passenger.js
    - cloudlinux-selector restart --json --interpreter nodejs --user tcsjenja --app-root CENTAR-TRZNI/backend