---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tcsjenja/CENTAR-TRZNI
    - /bin/mkdir -p $DEPLOYPATH/backend
    - /bin/cp -R backend/. $DEPLOYPATH/backend/
    - /bin/rm -rf $DEPLOYPATH/build
    - /bin/cp -R build $DEPLOYPATH/
    - /bin/bash -lc 'source /home/tcsjenja/nodevenv/CENTAR-TRZNI/backend/18/bin/activate && cd /home/tcsjenja/CENTAR-TRZNI/backend && npm install --omit=dev'